### ISSUE TITLE
MS/MS display

### ISSUE THREAD

**Issue by dwheeler23** [mzmine/mzmine3#567] opened 2022-03-06 23:52 UTC
### Basic information

* My operating system: Windows 10.0.18363 Build 18363, 64 bit
* My MZmine version: MZMine 3.0.0beta

### What happened

Excellent new version! Unfortunately I can't get the MS/MS plot display to work (formerly called MS/MS visualizer). I've tried fiddling with all of the settings (axes, options, etc.), file selection, updating Java, etc. 

No error appears, it just doesn't fire up any visualizer once I click OK.

**Comment by SteffenHeu** [comment] 2022-03-07 08:57
Hey dwheeler, 

thank you for the bug reprot.
Can you please post the log output? You can find it via the "Show log file" button in the help menu.
Also: What kind of file raw data file are you using? Perhaps it might be good to upload the file somewhere so we can reproduce the error.

**Comment by robinschmid** [comment] 2022-03-07 09:29
Hey, thanks for the report. That's one of the modules I have never used or touched so far. 
There are plenty of options for MS/MS visualization but this one seems very different from the rest. 

During the change of the interfaces, we created the new visualizer but forgot to add it to the main window.  That's an easy fix. 
I suspect this will be in the next patch release 3.0.1-beta.

Keep up the good work and report what you experience.

Best Robin


![image](https://user-images.githubusercontent.com/10366914/157003955-e83bc85b-2596-47fe-9046-f579d1b296c6.png)

**Comment by robinschmid** [comment] 2022-03-07 09:30
Oh and updating java does not work because MZmine ships with its own java version. That's what modern java does.

**Closed** 2022-03-07 10:32 UTC

**Comment by dwheeler23** [comment] 2022-03-07 12:37
Thank you so much! This was using Thermo RAW files. Again, excellent new version, I really appreciate the wonderful tool you have all made. 

Best,
Doug
