### ISSUE TITLE
Issue with SIRIUS export module

### ISSUE THREAD

**Issue by BoryALX** [mzmine/mzmine3#913] opened 2022-09-23 12:09 UTC
### Basic information
* My MZmine version: 
MZmine V 3.2.8
* My operating system:
Windows 10 Pro Education, Version: 2004, OS build: 19041.1415, 64-bit

*java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

*R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

### What happened

After processing LC-MS/MS datas, I exported the mgf file for SIRIUS with the corresponding module in MZmine 3. 
A .mgf file was generated but it contained a very long list of MS1 instead of the usual couple of ions listed. This gives unconsistent results when using further downstream annotation with SIRIUS. 
* Please include all parameter values for the MZmine modules you used 
I attached the batch file I used. 

* Please upload an MZmine project file that demonstrates the problem you are reporting.
I attached the .mgf file (220914_SIRIUS_export.mgf)

Thank you
Alex
[Issue_files.zip](https://github.com/mzmine/mzmine3/files/9633320/Issue_files.zip)

**Comment by BoryALX** [comment] 2022-09-26 12:45
Additionally, the problem was already present when using MZmine 2.53 but could be avoided when the merge MS/MS option was ticked during the export stage:
![image](https://user-images.githubusercontent.com/91329611/192279753-1d96a0bc-bf10-4eca-ae28-8cc89ec6a158.png)
Alex

**Comment by SteffenHeu** [comment] 2022-10-01 09:26
It is full intentional that some ms1 ions get exported as well, so they can be used for molecular formula annotation. 

As long as the ms2s are there I don't think this is an issue.

**Comment by RemyMG** [comment] 2022-10-04 15:02
Hello everyone,

What @BoryALX is saying is that MGF file content differs depending on the MZmine version and I guess he (we) did not expected it. MZmine v2 was exporting only MS1 precursor ion and associated MS2 spectrum whereas MZmine v3 is exporting precursor ion + several MS1 ions as you told @SteffenHeu. See attached the exported MGF files for the same ion but different MZmine version.

We would be pleased @SteffenHeu if you can clarify what is the selection criterion for the MS1 ions now in MZmine v3 ? To what extent does it help with feature annotation in SIRIUS ?

Thank you for your help.

[feature295_MZmine3_2_8.txt](https://github.com/mzmine/mzmine3/files/9707441/feature295_MZmine3_2_8.txt)
[feature295_MZmine2_53.txt](https://github.com/mzmine/mzmine3/files/9707444/feature295_MZmine2_53.txt)

**Comment by SteffenHeu** [comment] 2022-10-04 20:49
MZmine 3 will add features with correlating peak shape and their isotope pattern to the mgf (in case meta correlate and ion identity networking were applied). 
These can be multimers, different adducts or in-source fragments and can help SIRIUS with the molecular formula prediction.

I think if you dont want the correlated ions, you can do the export before the meta correlate and IIN step.

**Comment by robin1509** [comment] 2022-10-06 13:52
Sure ! I attach you the part of the .mgf concerning the feature 1070 I told you about before.

The ions from the isotopic pattern are :

247.1329 9.1E9
248.1361 1.5E9
249.1387 1.5E8

Hope that helps to solve the issue, don't hesitate if you need any other info.

[Feature_1070_export_SIRIUS.txt](https://github.com/mzmine/mzmine3/files/9725355/Feature_1070_export_SIRIUS.txt)

**Comment by Adafede** [comment] 2022-10-12 07:55
So cool to see those faces here!

@SteffenHeu In case there was some preliminary discussion here:

        @robinschmid After further investigation, it looks like something around https://github.com/mzmine/mzmine3/blob/c1924863edfc71bb8af9300e7d63fccba0a6d049/src/main/java/io/github/mzmine/modules/io/export_features_sirius/SiriusExportTask.java#L602-L604 is broken. The isotope patterns of correlated ions are not exported (see the example above, they are in the MS1 ions but not in the correlated ions).

_Originally posted by @Adafede in https://github.com/mzmine/mzmine3/issues/799#issuecomment-1203618638_

I think this should get some higher priority somehow, happy to help with some guidance!

**Comment by SteffenHeu** [comment] 2022-10-12 11:07
Hey, sorry for the late reply, i have too much other stuff to do, aswell.

I looked into the file and for me a different issue came up. There are two MS1 spectra exported, one with only the precursor peak and one with the correlated peaks.
When the file was imported as-is, only the spectrum with just the precursor signal was present. When i deleted the lines from the mgf, the correlated ions were imported, too.

In that case, the isotopic signals were recognized:
![grafik](https://user-images.githubusercontent.com/37407705/195327118-238ef0b2-f01c-4bb4-a3ae-7db915d17a5f.png)

I am running sirius 5.4.1. Which versions do you run?

**Comment by robin1509** [comment] 2022-10-12 11:37
Thank you for your answer.

Indeed, I didn't observe that “MSLEVEL=1” was present two times, once with a long list of ions and the other with only the parent mass. I also tried to remove the second list (the one with only the parent mass) and indeed the isotope pattern is recognized on Sirius (version 5.5.7). 

In summary, the problem really comes from the MZMine export... Wouldn't it be possible to go back to the export that was performed by MZMine 2.53 ?

**Comment by SteffenHeu** [comment] 2022-10-12 12:59
I noticed something else: 

we export the whole MS1 and the "correlated" ions indicated by the "SPECTYPE=CORRELATED MS" tag in the mgf. I think sirius prefers the correlated ions spectrum over the ms1 if there is one. this means either we should not export the correlated MS if there are no correlated ions or sirius has to check that during import.

@kaibioinfo / @mfleisch can you say if my assumption is correct? What is your preferred solution?

**Comment by Adafede** [comment] 2022-10-12 13:11
Having both correlated ions and (not necessarily correlated) isotopes together should also be an important option, I think.

**Comment by kaibioinfo** [comment] 2022-10-12 14:29
"CORRELATED MS" should contain all isotopes and adduct peaks - its the replacement of what SIRIUS would do itself when doing the preprocessing. The "MSLEVEL=1" spectrum was exported because Marcus needed it for zodiac? I have no clue. I don't think that it is even used in SIRIUS.

**Comment by SteffenHeu** [comment] 2022-10-13 06:39
Ok, i reached out to Marcus on slack, let's hope we have some clarity soon

**Comment by robinschmid** [comment] 2022-10-14 17:19
There was so much change on that module all the time.
But MS1, CORRELATED_MS and MS2 have been there for many versions. 
I think we should 
1. make it optional to export the correlated MS
2. only export one if the user actually ran isotope finder and ion identity networking. Otherwise its just limiting the info for SIRIUS

**Comment by Adafede** [comment] 2023-02-03 18:02
Hey,

I just tested the last dev version where I believe @SteffenHeu made some changes with the export.

I tested the SIRIUS export on the test `DOM_a.mzML` with the default parameters created by the watch wizard (can share them if needed).
I tested it on an ARM macOS and it led to the following: when ticking "merge", the file is empty, when not ticking it, only MSLEVEL=2 is exported without the correlated adducts/isotopes in MSLEVEL = 1.

It is somehow different from the previous export where isotopes were splitted from correlated adducts, but still not exactly what is expected I guess 😅

**Comment by SteffenHeu** [comment] 2023-02-03 18:54
I'll Look Into it on Monday

**Comment by Adafede** [comment] 2023-02-06 19:30
#1131 fixes it 😊

**Comment by Adafede** [comment] 2023-02-28 18:04
Hey,

Also looks like there is a small leftover difference between FBMN and SIRIUS exports:

In FBMN export, the "retention time" field is named `RTINSECONDS` (which looks standard, would keep it) but it is named only `RT` for SIRIUS.
Additionnally, the `SCANS` field which is often used by other tools is not exported in the SIRIUS export. It is a duplicate of `FEATURE_ID` but having it for compatibility with other pipelines would be great?

**Comment by robinschmid** [comment] 2023-02-28 18:53
So the problem with the SCANS field in GNPS is that it is just a replicate of the FEATURE_ID .
I think SCANS is supposed to point to the scan number in the file, which it does not in that export.

RTINSECONDS will be in the next release.  with this #1193 
### Format is this
```
BEGIN IONS
FEATURE_ID=1
MSLEVEL=1
RTINSECONDS=1.33
PEPMASS=154.99017
CHARGE=1+
SPECTYPE=CORRELATED MS
FILENAME=DOM_Interlab-LCMS_Lab15_A15M_Pos_MS2_rep2.mzML
SCANS=1
Num peaks=2
154.990173 100
155.993484 4.271
END IONS

BEGIN IONS
FEATURE_ID=1
MSLEVEL=2
RTINSECONDS=1.33
PEPMASS=154.99017
CHARGE=1+
MERGED_SCANS=10,35
MERGED_STATS=2 / 2 (0 removed due to low quality, 0 removed due to low cosine).
FILENAME=DOM_Interlab-LCMS_Lab15_A15M_Pos_MS2_rep2.mzML;DOM_Interlab-LCMS_Lab15_A15M_Pos_MS2_rep2.mzML
SCANS=1
Num peaks=51
55.93528 0.131
72.926903 0.145
72.937833 26.807
72.942642 0.129
72.949738 0.164
75.298103 0.084
77.543358 0.082
83.049713 0.094
84.534172 0.092
90.945686 0.12
90.948247 13.313
96.961479 0.149
100.943695 0.12
108.95866 5.636
111.044434 0.093
113.060165 0.094
113.853416 0.1
113.938286 0.172
113.943053 0.606
113.954399 0.139
113.964147 88.935
113.97123 0.185
113.973384 0.948
113.987676 0.622
115.968437 0.125
126.969064 0.259
127.075325 0.123
131.941971 0.142
131.94829 0.54
131.953438 2.63
131.96283 0.4
131.974522 100
131.978946 1.983
131.985452 0.932
131.9897 0.121
132.003853 0.672
133.978606 0.4
143.075729 0.081
145.989732 0.176
149.984997 1.983
154.907593 0.086
154.969343 3.019
154.975647 0.121
154.990276 5.294
155.033959 0.398
155.070291 1.952
155.085723 0.342
155.106812 0.09
155.1539 0.085
159.021727 0.194
172.00563 0.148
END IONS
```

**Closed** 2023-03-01 12:05 UTC
