### ISSUE TITLE
MZmine 3 is broken to the new masOS Ventura 13

### ISSUE THREAD

**Issue by gomespwp** [mzmine/mzmine3#1010] opened 2022-11-26 22:25 UTC
### Basic information

* My operating system and version: macOS venture 13
* My MZmine version: 3.2.8

### What happened

* After updating to macOS Ventura 13.0, MZmine 3 broke in my laptop, and also, when I tried to re-install it does not work anymore. 

I tried with the following codes, but both are broken (https://mzmine.github.io/mzmine_documentation/getting_started.html): 

sudo xattr -cr ../MZmine.app
# and
sudo xattr -cr MZmine.app

**Comment by tomas-pluskal** [comment] 2022-11-27 09:56
This is a duplicate of #978, please follow that issue instead.

**Closed by tomas-pluskal** 2022-11-27 09:56 UTC
