### ISSUE TITLE
cannot open .raw file in mzmine3 nor project made from .raw files

### ISSUE THREAD

**Issue by AnaKovacic** [mzmine/mzmine3#789] opened 2022-07-14 06:46 UTC
### Basic information

* My operating system: windows10
* My MZmine version: mzmine 3.1.0 beta

### What happened
I was creating the project with .raw data import, it was working just fine, than I was trying to export data directly to gnps, I was trying different things since I was not successfu. In one moment mzmine freezed, I end task in task manager, when I wasnted to reopen the project or import .raw I get the error:

![Posnetek zaslona 2022-07-14 084333 PNG](https://user-images.githubusercontent.com/72231221/178918687-dc96155d-f039-4f0c-b584-cb97c3c4cdd0.jpg)

**Comment by tomas-pluskal** [comment] 2022-07-14 06:48
Hi Ana,
could you share one .raw file that is failing for you?
Also, could you try this on another PC?

**Comment by AnaKovacic** [comment] 2022-07-14 06:58
Hi Tomaš,

This error appeared while I was working on my working stationary PC, I've
tried it on my laptop, and the same error occurred.
Project and .raw data with which I am working are stored on my google drive.
Then I tried on my home stationary PC where I have data on the computer and
it worked but when I copied the folder containing everything on the
computer at work, it again did not work.
Actually, none of the projects created from .raw files is working.

Please, find attached one .raw file.

Thank you for your help
 Blank_1.raw
<https://drive.google.com/file/d/1p2pkDSa4woCR0AvXw4eqZJZj_KtDHdnC/view?usp=drive_web>
.
Best
Ana

**Comment by tomas-pluskal** [comment] 2022-07-14 07:16
I tested your file and it works fine for me, so there should be nothing wrong with the .raw files.
MZmine is internally using the ThermoRawFileParser library.
Could you please try to download and unzip the library from here: https://github.com/mzmine/mzmine3/raw/master/src/main/resources/vendorlib/thermo/ThermoRawFileParser.zip
and run this command in the command line:
`ThermoRawFileParser.exe -i  Blank_1.raw`

**Comment by AnaKovacic** [comment] 2022-07-14 09:23
I did as suggested, it seems like it reads the file:

C:\Users\Ana>ThermoRawFileParser\ThermoRawFileParser.exe -i Blank_1.raw
2022-07-14 11:08:03 INFO Started parsing Blank_1.raw
2022-07-14 11:08:03 INFO Processing 7577 MS scans
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

2022-07-14 11:08:08 INFO Finished parsing Blank_1.raw

but the mzmine.exe app is still not working, giving the same error.
Also, it was working with no problem for 1 month, I haven't done sth that
would change the .raw files and I have tried with the ones from the local
disk as well.
The reinstallation of mzmine but still not working.

With mzml, everything there is no problem, I just don't want to lose the
project but luckily it is working on my third computer :).

Thank you.
Best
Ana

**Comment by tomas-pluskal** [comment] 2022-07-14 09:35
Hi Ana, thanks for the update. 
Could you please go to the MZmine menu Help -> Show log file and upload the complete log file here? (after you get the error message, of course).

**Comment by AnaKovacic** [comment] 2022-07-14 10:18
Sure,

Please find attached the log file.
Thank you.
Ana

**Comment by SteffenHeu** [comment] 2022-07-14 13:24
mh thats weird.
please upload an example project that reproduces the issue.

**Comment by AnaKovacic** [comment] 2022-07-14 14:48
Agree.
I thought it was sth with google drive, but then I copied the folder
containing raw files and project on the computer C disk, and the same error
appeared.
Please, find the link to the project:
https://drive.google.com/file/d/1xdPJAhyWQHjypXsNtY-uKpRETcUMbhf3/view?usp=sharing

**Comment by tomas-pluskal** [comment] 2022-07-14 15:08
Hi Ana, could you please try to delete this folder:
`C:\Users\Ana\AppData\Local\Temp\mzmine_thermo_raw_parser`
and after you delete it, try to run MZmine and import the files again?

**Comment by SteffenHeu** [comment] 2022-07-15 06:43
The project imports fine for me.

![grafik](https://user-images.githubusercontent.com/37407705/179166609-ab363654-8e7e-4acf-b6ec-a529c4fecee8.png)

could it be sth with the parser, tomas?

**Comment by tomas-pluskal** [comment] 2022-07-15 08:28
I believe the import issue should be fixed in my last pull request: https://github.com/mzmine/mzmine3/pull/790
That will probably also fix the project import.

**Comment by AnaKovacic** [comment] 2022-07-15 17:38
Tomas,
that is correct, after deleting the suggested folder, the project is
working normally.
Thank you.
Ana

**Comment by robinschmid** [comment] 2022-07-20 10:46
Great work. Seems to be fixed.

**Closed by robinschmid** 2022-07-20 10:46 UTC
