### ISSUE TITLE
RANSAC aligner doesn't seem to work on Windows 10 using Mzmine 3.0.11

### ISSUE THREAD

**Issue by Pumbalumba** [mzmine/mzmine3#640] opened 2022-03-31 06:19 UTC
### Basic information

* My operating system: Windows 10
* My MZmine version: 3.0.11

### What happened

When i click on RANSAC aligner it just doesn't open, can't use it in batch mode either.

**Comment by Pumbalumba** [comment] 2022-03-31 06:20
work on Windows 10 using Mzmine 3.0.10

**Comment by SteffenHeu** [comment] 2022-03-31 08:44
Please upload the log file ater trying to open the ransac aligner.

A potential fix can be to delete the configuration file under `C:\Users\<Username>\.mzmine3.conf` (must enable show hidden files)

**Comment by Pumbalumba** [comment] 2022-03-31 10:27
[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/8388437/mzmine_0_0.log)

**Comment by SteffenHeu** [comment] 2022-04-01 09:07
I cannot see any error that could have caused the dialog not to show up. Did deleting the configuration fix the issue?

Does the issue exist on multiple computers?

**Comment by Pumbalumba** [comment] 2022-04-01 11:02
The issue occured to at least 2 of my colleagues using Versions 3.0.0 and 3.0.11. For me the issue still occures in mzmine 3.0.21. Could you tell me how to enable show hidden files so I can try deleting the mzmine3.conf file?
[mzmine_0_0_3.0.21.log](https://github.com/mzmine/mzmine3/files/8396995/mzmine_0_0_3.0.21.log)

**Comment by Pumbalumba** [comment] 2022-04-01 11:08
Nevermind, I found out how to show hidden files.

**Comment by SteffenHeu** [comment] 2022-04-04 07:45
I'm sorry but i cannot reproduce the issue at the moment.

**Comment by Pumbalumba** [comment] 2022-04-04 11:55
I just figured out how to use RANSAC, for some reason it will only open when at least one feature list has been created using ADAP Chromatogram builder. It still does not open right after starting mzmine or when only raw data has been imported.

**Comment by SteffenHeu** [comment] 2022-04-04 12:49
Thanks! this helped a lot, i found the error. will be fixed with #651

**Closed by SteffenHeu** 2022-04-04 12:49 UTC
