### ISSUE TITLE
mzml export fails

### ISSUE THREAD

**Issue by hechth** [mzmine/mzmine3#710] opened 2022-06-02 14:07 UTC
### Basic information

* My operating system: Win10
* My MZmine version: 3.0.11-beta

### What happened
Steps:
1. Load mzml files
2. Raw data methods -> raw data filtering -> crop filter
3. Raw data methods -> raw data export -> export scans to mzml=> Error

The export simply doesn't start - also, even if multiple files are selected, a single output file is required.

**Comment by SteffenHeu** [comment] 2022-06-02 15:21
Hello hechth,

thanks for the report. I cannot reproduce the issue when i crop a file with these parameters:
![grafik](https://user-images.githubusercontent.com/37407705/171653951-a61278d5-bfca-45c5-89dc-1ca0e6bc098a.png)

please provide the example file and the parameters you used.

Are we talking about the same export? You select a folder path for the mzml export, so all selected files are exported to that folder.

**Comment by hechth** [comment] 2022-06-03 06:54
I chose the export scans to mzml export - the direct export as mzml works fine as well.

**Comment by SteffenHeu** [comment] 2022-06-03 09:11
Hi hechth,

ah i see. that issue was fixed alreadym but we havent published an official release since then. You can try the latest development build, which you can find here: https://github.com/mzmine/mzmine3/releases

I noticed the progress was not updated for the mzml export from scans, this will be fixed soon,

**Comment by hechth** [comment] 2022-06-03 09:22
Thanks for the quick response - I'll try the dev version then :)

**Closed** 2022-06-03 12:48 UTC

**Comment by hechth** [comment] 2022-06-07 09:54
I actually tested it now with the source code checked out from github master branch and I still observe the same error.
