### ISSUE TITLE
Raw Data Filter -> Crop Filter Function

### ISSUE THREAD

**Issue by emily-giedraitis** [mzmine/mzmine3#918] opened 2022-09-26 20:05 UTC
### Basic information

* My operating system: Windows 10
* My MZmine version: 3.2.8
* java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

*R version 4.2.1 (2022-06-23 ucrt) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

### What happened 
Would like to cut off retention times below 0.5 minutes and above 10 minutes as well as below 50 m/z and above 1500 m/z prior to assigning masses to my raw data. Filter sends off error code in screenshot below:
![image](https://user-images.githubusercontent.com/114430513/192345360-a79b7251-97e8-4f08-b370-1a0825827c22.png)

**Comment by Kevin-Murray** [comment] 2022-09-27 20:40
Good afternoon,

I am not able to reproduce this error with my own data.

Would you be able to provide more information about the raw data that is producing this error? Additionally, could you provide a complete screenshot of the Crop Filter parameters that you were using that produced this error message?

**Comment by tomas-pluskal** [comment] 2022-09-29 11:07
@emily-giedraitis Why did you close the issue?

**Comment by tomas-pluskal** [comment] 2022-09-29 16:40
Well, there is still an issue, because if you didn't fill the parameters correctly, the module should give a meaningful error message and not throw a NullPointerException. Maybe @omokshyna could double check this issue?

**Comment by emily-giedraitis** [comment] 2022-09-29 16:59
Okay here is a screenshot of the parameters of when it sent out the NullPointerException (also does this when MS level is set to 2): 
![image](https://user-images.githubusercontent.com/114430513/193091597-7557b58d-bebb-40ad-b80c-6ee1aff17d50.png)

and when the filter worked properly: 
![image](https://user-images.githubusercontent.com/114430513/193091872-c90abb62-df31-457b-aa91-8da74e39bcb5.png)

Also, if you select 0 for MS level (presumably all MS levels) it states "No Scans were detected". So the filter is only working for MS1 and not MS2.

**Comment by emily-giedraitis** [comment] 2022-09-29 17:14
Here are two of my raw data files I have been using to process:
[https://olucdenver-my.sharepoint.com/:f:/g/personal/emily_giedraitis_cuanschutz_edu/EgC6O_e6qtFMgYbuHysklvYBTozCg909G-AILjOJvdvdCQ?e=JrLLmT](url)
Let me know if the link does not work.

**Comment by omokshyna** [comment] 2022-09-30 11:23
Thanks, @emily-giedraitis! I will check with your files and get back to you.

**Comment by omokshyna** [comment] 2022-09-30 13:28
The main cause behind the problem is some empty MS2 scans in your data (that do not have associated m/z range). This leads to the error you encountered in Crop filter and should repeat if you attempt, for example, mass detection. I am now working on adding the warnings for this problem and additional option to filter out empty scans :)

**Comment by emily-giedraitis** [comment] 2022-09-30 17:01
Okay great. Not sure why those MS2 scans are empty since we are doing DDA so that new filter option will be helpful! Thank you.

**Closed** 2022-10-12 00:46 UTC
